#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
from itertools import count


#By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.


def fibonaccia(n):
    return 1 if n <= 2 else fibonaccia(n-1)+fibonaccia(n-2)


print(fibonaccia(10))